#!/bin/bash

TRACE_ID=$(uuidgen)
PROGRAM=""
PROGRAM_ARGS=""
STRACE_ARGS="0"
STRACE_ARG_LIST=""
ATTACH="0"

# Funciones
usage() {
  echo "scdebug.sh [-sto arg] [prog [arg1 ...]]"
}

arg_check() {
  while [ -n "$1" ]; do
    case "$1" in
      -sto )
        STRACE_ARGS="1"
        shift
        if [ -z "$1" ]; then
          usage
          exit 1
        fi
        STRACE_ARG_LIST="$1"
        ;;
      -nattch )
        ATTACH="1"
        ;;
      -* )
        usage
        exit 1
        ;;
      * )
        if [ -n "$PROGRAM" ]; then
          PROGRAM_ARGS+=" $1"
        else
          PROGRAM+="$1"
        fi
        ;;
    esac
    shift
  done
}
# Programa principal
arg_check "$@"

OUTPUT_FILE="$HOME/.scdebug/$PROGRAM/trace_$TRACE_ID.txt"
OUTPUT_DIR="$HOME/.scdebug/$PROGRAM"

# cat << _EOF_
#   $PROGRAM
# _EOF_

mkdir -p $OUTPUT_DIR && strace $STRACE_ARG_LIST -o $OUTPUT_FILE $PROGRAM $PROGRAM_ARGS